### ISSUE TITLE
Update Installation command

### ISSUE THREAD

**Issue by Rope-a-dope** [MasouShizuka/projects.yazi#3]
Should it be updated like this? 
```
ya pack -a MasouShizuka/projects
```
Otherwise, the error:

_Cloning into '/home/smallv/.local/state/yazi/packages/56dfe55221ec0587f8f0440e38bc4879'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/MasouShizuka/projects.yazi.yazi.git/'
Error: `git` command failed: exit status: 128_

**Comment by MasouShizuka** [comment]
Please refer to [cli](https://yazi-rs.github.io/docs/cli).

The error message you pointed out should be related to GitHub's authentication

**Comment by prosoitos** [comment]
I can confirm that the OP was correct. I just opened a PR.
